//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Href { get; set; }
        public string ImgPath { get; set; }
        public string Content { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Type { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Display { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int ViewCount { get; set; }
        public bool IsAlive { get; set; }
        public int CheckRule { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    }
}
